import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — Iris",
  description: "How Iris handles your data.",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0a] text-white">
      <header className="border-b border-[#1a1a1a] px-6 py-5 bg-[#0d0d0d]">
        <div className="max-w-3xl mx-auto">
          <Link
            href="/"
            className="text-[#666] text-[13px] hover:text-[#999] transition-colors"
          >
            ← Back to Iris
          </Link>
          <h1
            className="text-[26px] sm:text-[32px] tracking-tight mt-3"
            style={{ fontFamily: '"Times New Roman", Times, serif' }}
          >
            Iris
            <span className="text-[#555] font-normal ml-2">/ Privacy Policy</span>
          </h1>
          <p className="text-[#666] text-[13px] mt-2">Last updated: April 2026</p>
        </div>
      </header>

      <article className="max-w-3xl mx-auto px-6 py-8 space-y-8 text-[#E0E0E0] text-[15px] leading-relaxed">
        <p className="text-[#ccc]">
          Iris is built for people who are blind or have low vision. Your privacy matters,
          and we designed the app to keep as little of your data as possible. Iris comes
          in two versions — a web app at iris.how and a native iOS app on the App Store —
          and the two collect slightly different data. Both are covered below.
        </p>

        <Section title="Web app (iris.how): what we collect">
          <ul className="list-disc pl-5 space-y-3 marker:text-[#555]">
            <li>
              <span className="text-white">Camera frames</span> — sent to Google&apos;s Gemini
              API for visual analysis. Not stored permanently.
            </li>
            <li>
              <span className="text-white">Voice transcripts</span> — processed using
              Apple&apos;s Speech framework on your device or the Web Speech API in your
              browser. Sent along with the camera frame to Gemini so it knows what you
              asked.
            </li>
            <li>
              <span className="text-white">Audio responses</span> — generated by
              ElevenLabs&apos; text-to-speech API and played back to you. Not stored.
            </li>
            <li>
              <span className="text-white">Conversation history</span> — kept only in
              memory for the active session. Cleared when you close the app or tab.
            </li>
            <li>
              <span className="text-white">Location (GPS)</span> — collected only when
              your browser is sharing location and only for the optional hazard-logging
              feature. Not collected otherwise.
            </li>
            <li>
              <span className="text-white">No accounts, no emails</span>, no names, no
              personal information are required to use Iris on the web.
            </li>
          </ul>
        </Section>

        <Section title="iOS app: what we collect">
          <p className="mb-3">
            The iOS app on the App Store supports saved history across sessions, which
            means it needs a little more data than the web version. Here&apos;s exactly
            what it stores and where:
          </p>
          <ul className="list-disc pl-5 space-y-3 marker:text-[#555]">
            <li>
              <span className="text-white">Sign in with Apple</span> — if you choose to
              sign in with Apple, we receive a unique user identifier and, only if you
              choose to share it, your email address. We do not receive your Apple ID
              password or any other Apple account details. Apple&apos;s private email
              relay is supported — if you use it, we only ever see the relay address, not
              your real email.
            </li>
            <li>
              <span className="text-white">Guest sessions</span> — you can use Iris
              without signing in. A random, anonymous user ID is created so the app can
              save your history to your device and our database. No personal information
              is attached to a guest session.
            </li>
            <li>
              <span className="text-white">Conversation history</span> — for signed-in and
              guest users, every question you ask and every response Iris gives is saved
              to your account so you can review it later. Each saved entry includes your
              user ID, the transcript of your question, Iris&apos;s text response, and a
              timestamp. Camera frames themselves are <span className="text-white">not</span>{" "}
              saved with history.
            </li>
            <li>
              <span className="text-white">Camera frames</span> — same as on the web: sent
              to Gemini for analysis and discarded immediately after. Not retained.
            </li>
            <li>
              <span className="text-white">Voice transcripts</span> — generated on-device
              by Apple&apos;s Speech framework (no audio leaves your phone for
              transcription), then sent to Gemini with the camera frame so it can answer
              your question.
            </li>
            <li>
              <span className="text-white">Audio responses</span> — generated by
              ElevenLabs and played back. Not stored.
            </li>
            <li>
              <span className="text-white">Daily usage counter</span> — we count how many
              questions you&apos;ve asked today (resets each day) to enforce a 30-per-day
              limit. This counter is tied to your user ID and stores only a number and a
              date — no content.
            </li>
          </ul>
          <p className="mt-4">
            Saved data for the iOS app lives in a Supabase-hosted Postgres database. Every
            row is protected by row-level security rules so that only your account can
            read your data, and access is always over HTTPS.
          </p>
        </Section>

        <Section title="What we don't collect (either platform)">
          <ul className="list-disc pl-5 space-y-3 marker:text-[#555]">
            <li>No advertising identifiers, no tracking across apps or websites.</li>
            <li>No analytics about what you look at, ask, or when.</li>
            <li>No contact lists, no photos from your library, no files.</li>
            <li>No health, financial, or payment information.</li>
          </ul>
        </Section>

        <Section title="Data retention">
          <ul className="list-disc pl-5 space-y-3 marker:text-[#555]">
            <li>
              Camera frames are sent to Gemini and discarded immediately after processing,
              on both web and iOS.
            </li>
            <li>
              On the <span className="text-white">web</span>, voice transcripts live in
              memory only during your session and are discarded when you close the tab.
            </li>
            <li>
              On <span className="text-white">iOS</span>, transcripts and Iris&apos;s text
              responses are saved to your account so you can see them in History. They are
              kept until you delete them (or delete your account).
            </li>
            <li>Nothing is sold or shared with advertisers.</li>
          </ul>
        </Section>

        <Section title="Third-party processors">
          <p className="mb-3">
            To function, Iris sends data to a small number of services. Each has its own
            privacy practices:
          </p>
          <ul className="list-disc pl-5 space-y-3 marker:text-[#555]">
            <li>
              <span className="text-white">Google (Gemini API)</span> — processes camera
              frames and your spoken question. Subject to{" "}
              <ExtLink href="https://policies.google.com/privacy">
                Google&apos;s Privacy Policy
              </ExtLink>
              .
            </li>
            <li>
              <span className="text-white">ElevenLabs</span> — converts Iris&apos; text
              responses into speech. Subject to{" "}
              <ExtLink href="https://elevenlabs.io/privacy">
                ElevenLabs&apos; Privacy Policy
              </ExtLink>
              .
            </li>
            <li>
              <span className="text-white">Vercel</span> — hosts iris.how and serves the
              web app. Subject to{" "}
              <ExtLink href="https://vercel.com/legal/privacy-policy">
                Vercel&apos;s Privacy Policy
              </ExtLink>
              .
            </li>
            <li>
              <span className="text-white">Supabase (iOS only)</span> — stores your iOS
              account, saved history, and daily usage counter. Subject to{" "}
              <ExtLink href="https://supabase.com/privacy">
                Supabase&apos;s Privacy Policy
              </ExtLink>
              .
            </li>
            <li>
              <span className="text-white">Apple (iOS only)</span> — Sign in with Apple
              authenticates you without sharing your password. Subject to{" "}
              <ExtLink href="https://www.apple.com/legal/privacy/">
                Apple&apos;s Privacy Policy
              </ExtLink>
              .
            </li>
          </ul>
        </Section>

        <Section title="Your rights">
          <ul className="list-disc pl-5 space-y-3 marker:text-[#555]">
            <li>
              <span className="text-white">Web:</span> because iris.how doesn&apos;t
              require an account, there is no stored personal data for you to view or
              delete on our end. You can revoke camera, microphone, or location access at
              any time through your browser&apos;s site-settings menu.
            </li>
            <li>
              <span className="text-white">iOS — see your data:</span> everything Iris has
              saved for you is visible in the app&apos;s History screen.
            </li>
            <li>
              <span className="text-white">iOS — delete your data:</span> open Settings in
              the iOS app and tap &quot;Delete account.&quot; This permanently erases your
              account, your entire history, and your usage counter from our database. The
              deletion is immediate and irreversible.
            </li>
            <li>
              <span className="text-white">iOS — revoke permissions:</span> open the Apple
              Settings app → Iris → toggle off Camera, Microphone, or Speech Recognition
              at any time.
            </li>
            <li>
              <span className="text-white">iOS — revoke Sign in with Apple:</span> Apple
              Settings app → your name → Sign in with Apple → Iris → &quot;Stop Using
              Apple ID.&quot;
            </li>
          </ul>
        </Section>

        <Section title="Children's privacy">
          <p>
            Iris is not intended for children under 13, and we do not knowingly collect
            data from anyone under 13.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about this policy, your data, or accessibility concerns? Email{" "}
            <a
              href="mailto:raghavt@tamu.edu"
              className="text-[#4FC3F7] hover:underline underline-offset-2"
            >
              raghavt@tamu.edu
            </a>
            .
          </p>
        </Section>

        <Section title="Changes">
          <p>
            If this policy changes, the updated version will be posted at{" "}
            <a
              href="https://iris.how/privacy"
              className="text-[#4FC3F7] hover:underline underline-offset-2"
            >
              iris.how/privacy
            </a>{" "}
            with a new &quot;Last updated&quot; date. For material changes, we&apos;ll do
            our best to notify regular users in the app itself.
          </p>
        </Section>
      </article>

      <footer className="border-t border-[#1a1a1a] px-6 py-6 mt-8">
        <div className="max-w-3xl mx-auto flex items-center justify-between text-[12px] text-[#444]">
          <span>Iris &bull; iris.how</span>
          <div className="flex gap-4">
            <Link href="/terms" className="hover:text-[#888] transition-colors">
              Terms
            </Link>
            <Link href="/support" className="hover:text-[#888] transition-colors">
              Support
            </Link>
          </div>
        </div>
      </footer>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-white text-[18px] font-semibold tracking-tight mb-3">{title}</h2>
      <div className="text-[#ccc]">{children}</div>
    </section>
  );
}

function ExtLink({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="text-[#4FC3F7] hover:underline underline-offset-2"
    >
      {children}
    </a>
  );
}
